import React, { useState } from "react";

function ExerciseList() {
  const addExercise = function (e) {
    e.preventDefault();
    console.log("Add Another Exercise Clicked");
    // TODO: use State to push additional exercise nodes
    // TODO: find a way to assign them unique id's. Probably another useState call that's an exercise counter
  };

  const removeExercise = function (e) {
    e.preventDefault();
    console.log("Remove exercise clicked");
    // TODO: grab parent div id and delete; adjust state to splice the object
  };

  return (
    <div>
      <div>
        {/* this is an individual exercise node generated by default */}
        <label htmlFor="exercises">
          Choose an exercise (or input your own!)
        </label>
        <input list="exercises" name="exercise" id="exercise"></input>
        <datalist id="exercises">
          <option value="">Choose one</option>
          <option value="Bench Press">Bench Press</option>
          <option value="Biking">Biking</option>
          <option value="Crossfit">Crossfit</option>
          <option value="Deadlift">Deadlift</option>
          <option value="Dumbbell Bench Press">Dumbbell Bench Press</option>
          <option value="Dumbbell Curl">Dumbbell Curl</option>
          <option value="Dumbbell Row">Dumbbell Row</option>
          <option value="Exercise Bike">Exercise Bike</option>
          <option value="Hiking">Hiking</option>
          <option value="Jump Rope">Jump Rope</option>
          <option value="Pullup">Pullup</option>
          <option value="Plank">Plank</option>
          <option value="Pushup">Pushup</option>
          <option value="Rowing">Rowing</option>
          <option value="Running">Running</option>
          <option value="Situp">Situp</option>
          <option value="Stair Climb">Stair Climb</option>
          <option value="Squats">Squats</option>
          <option value="Walking">Walking</option>
        </datalist>
        {/* TODO: TYPE (time, sets/reps, distance(add stopwatch?)) */}
        {/* TODO: icon select (return string of local link) */}

        <button onClick={removeExercise}>Remove</button>
      </div>
      {/* button to add another individual exercise node */}
      <button onClick={addExercise}>Add another exercise</button>
    </div>
  );
}

export default ExerciseList;
